# Generated by Django 2.2.8 on 2019-12-18 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='student',
            name='campus',
        ),
        migrations.AddField(
            model_name='employee',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Faculty'),
        ),
        migrations.AddField(
            model_name='student',
            name='cursus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Cursus'),
        ),
    ]
