# Generated by Django 2.2.10 on 2020-03-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200308_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='company_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='office',
            field=models.CharField(max_length=255),
        ),
    ]
