# Generated by Django 2.2.10 on 2020-04-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200413_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursus',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
