# Generated by Django 2.2.8 on 2019-12-09 00:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('localization', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(max_length=180, null=True)),
                ('url_redirection', models.URLField(blank=True, max_length=740)),
                ('language', models.CharField(choices=[('FR', 'French'), ('EN', 'English')], default='FR', max_length=2)),
                ('job_offer', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('FRE', 'Freelance'), ('STA', 'Stage'), ('ALT', 'Alternance'), ('FUL', 'Temps plein'), ('HAL', 'Temps partiel')], default='CDI', max_length=3)),
                ('job_fields', models.CharField(choices=[('UI', 'UI design'), ('FE', 'Front-end development'), ('BA', 'Back-end development'), ('AP', 'App Development'), ('AR', 'Information Architecture'), ('CS', 'Content Strategy'), ('MA', 'Management'), ('SM', 'Social Media Expert'), ('MI', 'Miscellary')], default='UI', max_length=2)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Enterprise')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ('published_date',),
            },
        ),
    ]
