# Generated by Django 2.2.8 on 2019-12-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_objectviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='job_time',
            field=models.CharField(choices=[('FUL', 'Temps plein'), ('HAL', 'Temps partiel')], default='FUL', max_length=3),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='job_offer',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('FRE', 'Freelance'), ('STA', 'Stage'), ('ALT', 'Alternance')], default='CDI', max_length=3),
        ),
    ]
