# Generated by Django 2.2.10 on 2020-03-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0003_auto_20191225_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='contact_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='job_description',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='requirements',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
