# Generated by Django 2.2.10 on 2020-03-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0004_auto_20200308_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectViewed',
        ),
    ]
