export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';

export const RESET_AUTH_LOGIN_USER_FAILURE = 'RESET_AUTH_LOGIN_USER_FAILURE';

export const RESPONSIVE_DRAWER_OPEN = 'RESPONSIVE_DRAWER_OPEN';
export const RESPONSIVE_DRAWER_CLOSE = 'RESPONSIVE_DRAWER_CLOSE';
